import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export type RoadmapFeature = {
  id: string;
  title: string;
  status: string;
  phase?: string;
  progress?: number;
  currentStage?: string;
  summary?: string;
  why?: string;
  scope?: string[];
  outOfScope?: string[];
  stages?: Array<{ id: string; title: string; status: string; updatedAt?: string }>;
  updates?: Array<{ date: string; kind: string; text: string }>;
  links?: Array<{ label: string; href: string }>;
  notePath?: string;
  resumePoint?: string;
  nextActions?: string[];
  lastWorkedAt?: string;
  updatedAt?: string;
};

export type RoadmapDocument = {
  updatedAt?: string;
  statusOrder?: string[];
  stageStatusOrder?: string[];
  features: RoadmapFeature[];
};

export const ROADMAP_JSON = "docs/roadmap.json";
export const ROADMAP_MD = "docs/roadmap.md";
const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const ROADMAP_JSON_PATH = join(REPO_ROOT, ROADMAP_JSON);
const ROADMAP_MD_PATH = join(REPO_ROOT, ROADMAP_MD);

export function readRoadmapMarkdown(): string {
  return readFileSync(ROADMAP_MD_PATH, "utf8");
}

const DEFAULT_STATUS_ORDER = ["now", "next", "planned", "exploring", "deferred", "shipped"];
const FEATURE_STATUSES = new Set(DEFAULT_STATUS_ORDER);
const STAGE_STATUSES = new Set(["planned", "next", "now", "done", "blocked", "cut"]);

export function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

export function readRoadmap(): RoadmapDocument {
  const roadmap = JSON.parse(readFileSync(ROADMAP_JSON_PATH, "utf8")) as RoadmapDocument;
  if (!Array.isArray(roadmap.features)) throw new Error(`${ROADMAP_JSON} missing features array`);
  return roadmap;
}

export function writeRoadmap(roadmap: RoadmapDocument): void {
  roadmap.updatedAt = todayIsoDate();
  writeFileSync(ROADMAP_JSON_PATH, `${JSON.stringify(roadmap, null, 2)}\n`, "utf8");
}

export function findFeature(roadmap: RoadmapDocument, featureId: string): RoadmapFeature {
  const feature = roadmap.features.find((item) => item.id === featureId);
  if (!feature) throw new Error(`feature not found: ${featureId}`);
  return feature;
}

function lines(items: string[] | undefined): string {
  if (!items || items.length === 0) return "- None listed.\n";
  return items.map((item) => `- ${item}`).join("\n") + "\n";
}

function renderStages(stages: RoadmapFeature["stages"]): string {
  if (!stages || stages.length === 0) return "- None listed.\n";
  return stages
    .map((stage) => `- ${stage.status}: ${stage.title}${stage.updatedAt ? ` (${stage.updatedAt})` : ""}`)
    .join("\n") + "\n";
}

function renderUpdates(updates: RoadmapFeature["updates"]): string {
  if (!updates || updates.length === 0) return "- None listed.\n";
  return updates
    .slice(-5)
    .reverse()
    .map((update) => `- ${update.date} ${update.kind}: ${update.text}`)
    .join("\n") + "\n";
}

function renderLinks(feature: RoadmapFeature): string {
  const links = [...(feature.links ?? [])];
  if (feature.notePath && !links.some((link) => link.href === feature.notePath)) {
    links.unshift({ label: "Feature note", href: feature.notePath });
  }
  if (links.length === 0) return "- None listed.\n";
  return links.map((link) => `- [${link.label}](${link.href})`).join("\n") + "\n";
}

function renderFeature(feature: RoadmapFeature): string {
  return `### ${feature.title}

Feature ID: \`${feature.id}\`
Status: \`${feature.status}\`
Phase: ${feature.phase ?? "Unphased"}
Progress: ${feature.progress ?? 0}
Current stage: ${feature.currentStage ?? "Not started"}
Last worked: ${feature.lastWorkedAt ?? "Unknown"}

Resume point:
${feature.resumePoint ?? "None recorded."}

Summary:
${feature.summary ?? ""}

Why:
${feature.why ?? ""}

Next actions:
${lines(feature.nextActions)}
Scope:
${lines(feature.scope)}
Out of scope:
${lines(feature.outOfScope)}
Stages:
${renderStages(feature.stages)}
Recent updates:
${renderUpdates(feature.updates)}
Links:
${renderLinks(feature)}
`;
}

export function renderRoadmapMarkdown(data: RoadmapDocument): string {
  const order = data.statusOrder ?? DEFAULT_STATUS_ORDER;
  const features = Array.isArray(data.features) ? data.features : [];
  const sections = order
    .map((status) => {
      const group = features.filter((feature) => feature.status === status);
      if (group.length === 0) return "";
      return `## ${status}

${group.map(renderFeature).join("\n")}`;
    })
    .filter(Boolean)
    .join("\n");

  return `<!-- Generated by scripts/export-roadmap.ts. Do not edit by hand. -->

# lumen Roadmap For Agents

Generated: ${todayIsoDate()}
Source: ${ROADMAP_JSON}
Roadmap updated: ${data.updatedAt ?? "unknown"}

## Agent Rules

- Read AGENTS.md first.
- Treat docs/project-status.md as implementation source of truth.
- Use this file for feature-stage coordination and resume context.
- Update roadmap only at feature-stage boundaries.
- Do not build deferred features unless the user explicitly reopens them.
- Prefer feature notes for deep context and this file for quick orientation.

${sections}`;
}

export function exportRoadmapMarkdown(roadmap = readRoadmap()): void {
  writeFileSync(ROADMAP_MD_PATH, renderRoadmapMarkdown(roadmap), "utf8");
}

export function assertFeatureStatus(status: string): void {
  if (!FEATURE_STATUSES.has(status)) throw new Error(`invalid feature status: ${status}`);
}

export function assertStageStatus(status: string): void {
  if (!STAGE_STATUSES.has(status)) throw new Error(`invalid stage status: ${status}`);
}
